export enum FieldNameLayoutGeneral {
    layout = 'layoutGeneral.layout',
    defaultStyles = 'layoutGeneral.defaultStyles',
    columns = 'layoutGeneral.layout.columns',
    marge = 'layoutGeneral.layout.marge',
    space = 'layoutGeneral.layout.space',
    withPhoto = 'layoutGeneral.layout.withPhoto',
    stylePhoto = 'layoutGeneral.layout.stylePhoto',
    titleSection = 'layoutGeneral.layout.titleSection',
    textTransform = 'layoutGeneral.layout.titleSection.textTransform',
    withIcon = 'layoutGeneral.layout.titleSection.withIcon',
    iconStyle = 'layoutGeneral.layout.titleSection.iconStyle',
    withLigneDessous = 'layoutGeneral.layout.titleSection.withLigneDessous',
    withLigneDessus = 'layoutGeneral.layout.titleSection.withLigneDessus',
    primaryColor = 'layoutGeneral.defaultStyles.primaryColor',
    slugTemplate = 'layoutGeneral.defaultStyles.slugTemplate',
    components = 'layoutGeneral.defaultStyles.components',
    sectionHeader = 'layoutGeneral.defaultStyles.components.sectionHeader',
    sectionHeaderTitle = 'layoutGeneral.defaultStyles.components.sectionHeader.title',
    sectionHeaderSubTitle = 'layoutGeneral.defaultStyles.components.sectionHeader.subTitle',
    sectionHeaderContent = 'layoutGeneral.defaultStyles.components.sectionHeader.content',
    sectionHeaderNom = 'layoutGeneral.defaultStyles.components.sectionHeader.nom',
    sectionHeaderPrenom = 'layoutGeneral.defaultStyles.components.sectionHeader.prenom',
}