export enum FieldNameHeader {
    header = 'datas.header',
    title = 'datas.header.title',
    subTitle = 'datas.header.subtitle',
    content = 'datas.header.content',
    nom = 'datas.header.nom',
    prenom = 'datas.header.prenom',
    email = 'datas.header.email',
    phone = 'datas.header.phone',
    location = 'datas.header.location',
    settings = 'datas.header.settings',
    settingsTitle = 'datas.header.settings.title',
    settingsSubTitle = 'datas.header.settings.subTitle',
    settingsContent = 'datas.header.settings.content',
    settingsNom = 'datas.header.settings.nom',
    settingsPrenom = 'datas.header.settings.prenom',
}