import { 
    FaFacebook, 
    FaFacebookF, 
    FaFacebookSquare, 
    FaGlobe, 
    FaInstagram, 
    FaInstagramSquare, 
    FaLinkedin, 
    FaLinkedinIn, 
    FaTwitter, 
    FaTwitterSquare, 
    FaYoutube, 
    FaPinterestP,
    FaPinterestSquare,
    FaPinterest,
    FaGooglePlusG,
    FaGooglePlusSquare,
    FaGooglePlus,
    FaBehanceSquare,
    FaBehance,
    FaGitSquare,
    FaGit,
    FaGithubAlt,
    FaGithubSquare,
    FaGithub,
    FaGitlab,
    FaSkype,
    FaVimeoV,
    FaVimeo,
    FaWhatsappSquare,
    FaStackOverflow,
    FaDiscord,
    FaSpotify,
    FaSoundcloud
} from "react-icons/fa";

export const socialIconsRegister: Record<string, React.ComponentType<{ style?: React.CSSProperties }>> = {
    faGlobe: FaGlobe,
    faFacebookSquare: FaFacebookSquare,
    faFacebook: FaFacebook,
    faFacebookF: FaFacebookF,
    faInstagram: FaInstagram,
    faInstagramSquare: FaInstagramSquare,
    faLinkedinIn: FaLinkedinIn,
    faLinkedin: FaLinkedin,
    faYoutube: FaYoutube,
    faPinterestP: FaPinterestP,
    faPinterestSquare: FaPinterestSquare,   
    faPinterest: FaPinterest,
    faTwitterSquare: FaTwitterSquare,
    faTwitter: FaTwitter,
    faGooglePlusG: FaGooglePlusG,
    faGooglePlusSquare: FaGooglePlusSquare,
    faGooglePlus: FaGooglePlus,
    faBehanceSquare: FaBehanceSquare,
    faBehance: FaBehance,
    faGitSquare: FaGitSquare,
    faGit: FaGit,
    faGithubAlt: FaGithubAlt,
    faGithubSquare: FaGithubSquare,
    faGithub: FaGithub,
    faGitlab: FaGitlab,
    faSkype: FaSkype,
    faVimeoV: FaVimeoV,
    faVimeo: FaVimeo,
    faWhatsappSquare: FaWhatsappSquare,
    faStackOverflow: FaStackOverflow,
    faDiscord: FaDiscord,
    faSpotify: FaSpotify,
    faSoundcloud: FaSoundcloud,
}