import type { IconType } from "react-icons";
import {
  FaGlobe,
  FaPlus,
  FaCheck,
  FaSearch,
  FaEye,
  FaMapMarkedAlt,
  FaMapSigns,
  FaCog,
  FaCogs,
  FaFolderOpen,
  FaEnvelope,
  FaSave,
  FaPaperclip,
  FaInfinity,
  FaWrench,
  FaThumbsUp,
  FaLink,
  FaCrosshairs,
  FaStar,
  FaStarHalfAlt,
  FaRegStar,
  FaKey,
  FaWindows,
  FaApple,
  FaGithub,
  FaBook,
  FaPen,
  FaPaintBrush,
  FaCalendar,
  FaBell,
  FaTools,
  FaPhone,
  FaClock,
  FaLightbulb,
  FaBatteryThreeQuarters,
  FaDesktop,
  FaMobileAlt,
  FaCameraRetro,
  FaCamera,
  FaFileAlt,
  FaRulerCombined,
  FaCloud,
  FaCloudRain,
  FaSun,
  FaSitemap,
  FaRobot,
  FaCode,
  FaDatabase,
  FaShareAlt,
  FaServer,
  FaHeadset,
  FaProjectDiagram,
  FaPaperPlane,
  FaPlane,
  FaRocket,
  FaGavel,
  FaHourglassStart,
  FaDollarSign,
  FaBitcoin,
  FaGlobeEurope,
  FaTruck,
  FaCar,
  FaTachometerAlt,
  FaUserAstronaut,
  FaMusic,
  FaGuitar,
  FaHeadphones,
  FaMicrophone,
  FaSprayCan,
  FaUserGraduate,
  FaMedal,
  FaAward,
  FaTrophy,
  FaGem,
  FaFlagCheckered,
  FaCrown,
  FaMicroscope,
  FaFlask,
  FaCertificate,
  FaGraduationCap,
  FaShoppingCart,
  FaTag,
  FaPuzzlePiece,
  FaChartLine,
  FaChartPie,
  FaSignal,
  FaFilm,
  FaBullhorn,
  FaSuitcase,
  FaGamepad,
  FaHiking,
  FaHome,
  FaFootballBall,
  FaRunning,
  FaMountain,
  FaTableTennis,
  FaYinYang,
  FaWeight,
  FaSwimmer,
  FaVolleyballBall,
  FaBasketballBall,
  FaBaseballBall,
  FaFutbol,
  FaSnowflake,
  FaSnowboarding,
  FaBiking,
  FaGolfBall,
  FaBowlingBall,
  FaChessKnight,
  FaAnchor,
  FaDice,
  FaFire,
  FaHeart,
  FaSmileBeam,
  FaMagic,
  FaGlassMartini,
  FaBinoculars,
  FaQuoteRight,
  FaUserFriends,
  FaBrain,
  FaDog,
  FaCarrot,
  FaSeedling,
  FaPepperHot,
  FaLeaf,
  FaAppleAlt,
  FaRecycle,
  FaPeace,
  FaAirFreshener,
  FaHorse,
  FaHandsHelping,
  FaWheelchair,
  FaRibbon,
  FaHandHoldingHeart,
  FaTshirt,
} from "react-icons/fa";

export const basicIconsRegister: Record<string, IconType> = {
  faGlobe: FaGlobe,
  faPlus: FaPlus,
  faCheck: FaCheck,
  faSearch: FaSearch,
  faEye: FaEye,
  faMapMarkedAlt: FaMapMarkedAlt,
  faMapSigns: FaMapSigns,
  faCog: FaCog,
  faCogs: FaCogs,
  faFolderOpen: FaFolderOpen,
  faEnvelope: FaEnvelope,
  faSave: FaSave,
  faPaperclip: FaPaperclip,
  faInfinity: FaInfinity,
  faWrench: FaWrench,
  faThumbsUp: FaThumbsUp,
  faLink: FaLink,
  faCrosshairs: FaCrosshairs,
  faStar: FaStar,
  faStarHalfAlt: FaStarHalfAlt,
  faRegStar: FaRegStar,
  faKey: FaKey,
  faWindows: FaWindows,
  faApple: FaApple,
  faGithub: FaGithub,
  faBook: FaBook,
  faPen: FaPen,
  faPaintBrush: FaPaintBrush,
  faCalendar: FaCalendar,
  faBell: FaBell,
  faTools: FaTools,
  faPhone: FaPhone,
  faClock: FaClock,
  faLightbulb: FaLightbulb,
  faBatteryThreeQuarters: FaBatteryThreeQuarters,
  faDesktop: FaDesktop,
  faMobileAlt: FaMobileAlt,
  faCameraRetro: FaCameraRetro,
  faCamera: FaCamera,
  faFileAlt: FaFileAlt,
  faRulerCombined: FaRulerCombined,
  faCloud: FaCloud,
  faCloudRain: FaCloudRain,
  faSun: FaSun,
  faSitemap: FaSitemap,
  faRobot: FaRobot,
  faCode: FaCode,
  faDatabase: FaDatabase,
  faShareAlt: FaShareAlt,
  faServer: FaServer,
  faHeadset: FaHeadset,
  faProjectDiagram: FaProjectDiagram,
  faPaperPlane: FaPaperPlane,
  faPlane: FaPlane,
  faRocket: FaRocket,
  faGavel: FaGavel,
  faHourglassStart: FaHourglassStart,
  faDollarSign: FaDollarSign,
  faBitcoin: FaBitcoin,
  faGlobeEurope: FaGlobeEurope,
  faTruck: FaTruck,
  faCar: FaCar,
  faTachometerAlt: FaTachometerAlt,
  faUserAstronaut: FaUserAstronaut,
  faMusic: FaMusic,
  faGuitar: FaGuitar,
  faHeadphones: FaHeadphones,
  faMicrophone: FaMicrophone,
  faSprayCan: FaSprayCan,
  faUserGraduate: FaUserGraduate,
  faMedal: FaMedal,
  faAward: FaAward,
  faTrophy: FaTrophy,
  faGem: FaGem,
  faFlagCheckered: FaFlagCheckered,
  faCrown: FaCrown,
  faMicroscope: FaMicroscope,
  faFlask: FaFlask,
  faCertificate: FaCertificate,
  faGraduationCap: FaGraduationCap,
  faShoppingCart: FaShoppingCart,
  faTag: FaTag,
  faPuzzlePiece: FaPuzzlePiece,
  faChartLine: FaChartLine,
  faChartPie: FaChartPie,
  faSignal: FaSignal,
  faFilm: FaFilm,
  faBullhorn: FaBullhorn,
  faSuitcase: FaSuitcase,
  faGamepad: FaGamepad,
  faHiking: FaHiking,
  faHome: FaHome,
  faFootballBall: FaFootballBall,
  faRunning: FaRunning,
  faMountain: FaMountain,
  faTableTennis: FaTableTennis,
  faYinYang: FaYinYang,
  faWeight: FaWeight,
  faSwimmer: FaSwimmer,
  faVolleyballBall: FaVolleyballBall,
  faBasketballBall: FaBasketballBall,
  faBaseballBall: FaBaseballBall,
  faFutbol: FaFutbol,
  faSnowflake: FaSnowflake,
  faSnowboarding: FaSnowboarding,
  faBiking: FaBiking,
  faGolfBall: FaGolfBall,
  faBowlingBall: FaBowlingBall,
  faChessKnight: FaChessKnight,
  faAnchor: FaAnchor,
  faDice: FaDice,
  faFire: FaFire,
  faHeart: FaHeart,
  faSmileBeam: FaSmileBeam,
  faMagic: FaMagic,
  faGlassMartini: FaGlassMartini,
  faBinoculars: FaBinoculars,
  faQuoteRight: FaQuoteRight,
  faUserFriends: FaUserFriends,
  faBrain: FaBrain,
  faDog: FaDog,
  faCarrot: FaCarrot,
  faSeedling: FaSeedling,
  faPepperHot: FaPepperHot,
  faLeaf: FaLeaf,
  faAppleAlt: FaAppleAlt,
  faRecycle: FaRecycle,
  faPeace: FaPeace,
  faAirFreshener: FaAirFreshener,
  faHorse: FaHorse,
  faHandsHelping: FaHandsHelping,
  faWheelchair: FaWheelchair,
  faRibbon: FaRibbon,
  faHandHoldingHeart: FaHandHoldingHeart,
  faTshirt: FaTshirt,
};