import { prismaTest } from '../../lib/prismaTest';

export async function resetTestDB() {
  // supprime tout ce qui existe pour repartir à zéro
  await prismaTest.$transaction([
    prismaTest.cV.deleteMany(),
    prismaTest.cVModule.deleteMany(),
    prismaTest.cVModuleItem.deleteMany(),
    prismaTest.cVTemplate.deleteMany(),
    prismaTest.formation.deleteMany(),
    prismaTest.cvFormation.deleteMany(),
    prismaTest.certification.deleteMany(),
    prismaTest.cvCertification.deleteMany(),
    prismaTest.price.deleteMany(),
    prismaTest.cvPrice.deleteMany(),
    prismaTest.expertise.deleteMany(),
    prismaTest.cvExpertise.deleteMany(),
    prismaTest.philosophy.deleteMany(),
    prismaTest.cvPhilosophy.deleteMany(),
    prismaTest.socialMedia.deleteMany(),
    prismaTest.cvSocialMedia.deleteMany(),
    prismaTest.language.deleteMany(),
    prismaTest.cvLanguage.deleteMany(),
    prismaTest.publication.deleteMany(),
    prismaTest.cvPublication.deleteMany(),
    prismaTest.missionProject.deleteMany(),
    prismaTest.cvMissionProject.deleteMany(),
    prismaTest.project.deleteMany(),
    prismaTest.cvProject.deleteMany(),
    prismaTest.missionVolunteering.deleteMany(),
    prismaTest.cvMissionVolunteering.deleteMany(),
    prismaTest.volunteering.deleteMany(),
    prismaTest.cvVolunteering.deleteMany(),
    prismaTest.strength.deleteMany(),
    prismaTest.cvStrength.deleteMany(),
    prismaTest.achievement.deleteMany(),
    prismaTest.cvAchievement.deleteMany(),
    prismaTest.education.deleteMany(),
    prismaTest.cvEducation.deleteMany(),
    prismaTest.profileCompetence.deleteMany(),
    prismaTest.cvCompetence.deleteMany(),
    prismaTest.profileCompetenceGroup.deleteMany(),
    prismaTest.cvCompetenceGroup.deleteMany(),
    prismaTest.competence.deleteMany(),
    prismaTest.profileSkill.deleteMany(),
    prismaTest.cvSkill.deleteMany(),
    prismaTest.profileSkillGroup.deleteMany(),
    prismaTest.cvSkillGroup.deleteMany(),
    prismaTest.skill.deleteMany(),
    prismaTest.missionExperience.deleteMany(),
    prismaTest.cvMissionExperience.deleteMany(),
    prismaTest.experience.deleteMany(),
    prismaTest.cvExperience.deleteMany(),
    prismaTest.missionExperience.deleteMany(),
    prismaTest.description.deleteMany(),
    prismaTest.cvDescription.deleteMany(),
    prismaTest.profile.deleteMany(),
    prismaTest.cvHeader.deleteMany(),
    prismaTest.user.deleteMany(),
  ]);

  // ajoute ici d'autres entités si tu veux
}
