import { classiqueTokens, moderneTokens, minimalTokens } from "./themeTokens";
import {
	buildHeader,
	buildDescriptionModule,
	buildExperienceModule,
	buildEducationModule,
	buildSkillModule,
	buildLanguageModule,
	buildProjectModule,
	buildSocialMediaModule,
	buildStrengthModule,
	buildPhilosophyModule,
	buildFormationModule,
	buildCertificationModule,
	buildPrizeModule,
	buildPassionModule,
	buildExpertiseModule,
	buildVolunteeringModule,
	buildPublicationModule,
	buildAchievementModule,
	buildCompetenceModule,
	buildTagModule,
} from "./buildTemplateModules";
import type {
	CreateCvTemplateInput,
	createCvTemplateSchema,
	TemplateLayout,
  } from "@/services/schemas/cvTemplate.schema";
import type z from "zod";

type SeedTemplate = z.input<typeof createCvTemplateSchema>;

export const sharedLayout = {
	columns: 1,
	marge: "md",
	space: "md",
	withPhoto: false,
	stylePhoto: "flat",
	titleSection: {
		textTransform: "capitalize",
		withIcon: false,
		iconStyle: "flat",
		withLigneDessous: false,
		withLigneDessus: false,
		lineWeight: "sm",
		bottomSpaceLine: "sm",
		topSpaceLine: "sm",
		textAlign: "left",
	},
	typography: {
		fontFamily: "inter",
		roles: {
			body: "inter",
			headerTitle: "inter",
			headerSubTitle: "inter",
			sectionTitle: "inter",
		},
	},
	listStyle: "none"
} satisfies TemplateLayout;

export const seedTemplates = [
	{
		name: "Classique",
		structure: {
			layout: sharedLayout,
			header: buildHeader(classiqueTokens),
			modules: [
				buildDescriptionModule(classiqueTokens, { order: 1, title: "Profil" }),
				buildExperienceModule(classiqueTokens, {
					order: 2,
					title: "Expériences professionnelles",
				}),
				buildEducationModule(classiqueTokens, { order: 3, title: "Diplomes" }),
				buildLanguageModule(classiqueTokens, {
					order: 4,
					title: "Langues",
					design: "stars",
				}),
				buildSkillModule(classiqueTokens, {
					order: 5,
					title: "Skills",
					isActive: false,
				}),
				buildCompetenceModule(classiqueTokens, {
					order: 6,
					title: "Compétences",
					isActive: false,
				}),
				buildTagModule(classiqueTokens, {
					order: 7,
					title: "Tags",
					isActive: false,
				}),
				buildSocialMediaModule(classiqueTokens, {
					order: 8,
					title: "Réseaux sociaux",
					isActive: false,
				}),
				buildPassionModule(classiqueTokens, {
					order: 9,
					title: "Passions",
					isActive: false,
				}),
				buildProjectModule(classiqueTokens, {
					order: 10,
					title: "Projets",
					isActive: false,
				}),
				buildExpertiseModule(classiqueTokens, {
					order: 11,
					title: "Expertises",
					isActive: false,
				}),
				buildStrengthModule(classiqueTokens, {
					order: 12,
					title: "Atouts",
					isActive: false,
				}),
				buildPhilosophyModule(classiqueTokens, {
					order: 13,
					title: "Philosophie",
					isActive: false,
				}),
				buildFormationModule(classiqueTokens, {
					order: 14,
					title: "Formation",
					isActive: false,
				}),
				buildCertificationModule(classiqueTokens, {
					order: 15,
					title: "Certifications",
					isActive: false,
				}),
				buildPrizeModule(classiqueTokens, {
					order: 16,
					title: "Prix",
					isActive: false,
				}),
				buildPublicationModule(classiqueTokens, {
					order: 17,
					title: "Publications",
					isActive: false,
				}),
				buildAchievementModule(classiqueTokens, {
					order: 18,
					title: "Réalisations",
					isActive: false,
				}),
				buildVolunteeringModule(classiqueTokens, {
					order: 19,
					title: "Volontariat",
					isActive: false,
				}),
				// language / project : mêmes builders une fois leurs schemas prêts
			],
		},
		defaultStyles: {
			primaryColor: { name: "red", primary: "-600" },
			slugTemplate: "classique-noLine-x",
			components: {
				pageLayout: "OneColumnModel",
				sectionHeader: "HeaderOne",
				sectionExperience: {
					component: "SectionExperienceOne",
					miniature: "MiniExperienceOne",
					item: "CardExperienceOne",
					Label: "Expérience",
					icon: "BsListCheck",
				},
				sectionDescription: {
					component: "SectionDescriptionOne",
					miniature: "MiniDescriptionOne",
					Label: "Présentation",
					icon: "BsPerson",
				},
				sectionEducation: {
					component: "SectionEducationOne",
					miniature: "MiniEducationOne",
					item: "CardEducationOne",
					Label: "Diplome",
					icon: "MdSchool",
				},
				sectionSkill: {
					component: "SectionSkillOne",
					miniature: "MiniSkillOne",
					item: "CardSkillOne",
					group: "CardGroupSkillOne",
					Label: "Skill",
					icon: "MdTag",
				},
				sectionLanguage: {
					component: "SectionLanguageOne",
					miniature: "MiniLanguageOne",
					item: "CardLanguageOne",
					Label: "Langue",
					icon: "MdLanguage",
				},
				sectionProject: {
					component: "SectionProjectOne",
					miniature: "MiniProjectOne",
					item: "CardProjectOne",
					Label: "Projet",
					icon: "GoProject",
				},
				sectionSocialMedia: {
					component: "SectionSocialMediaOne",
					miniature: "MiniSocialMediaOne",
					item: "CardSocialMediaOne",
					Label: "Réseau social",
					icon: "FaGlobe",
				},
				sectionStrength: {
					component: "SectionStrengthOne",
					miniature: "MiniStrengthOne",
					item: "CardStrengthOne",
					Label: "Atouts",
					icon: "FaThumbsUp",
				},
				sectionPhilosophy: {
					component: "SectionPhilosophyOne",
					miniature: "MiniPhilosophyOne",
					Label: "Philosophie",
					icon: "FaQuoteLeft",
				},
				sectionFormation: {
					component: "SectionFormationOne",
					miniature: "MiniFormationOne",
					item: "CardFormationOne",
					Label: "Formation",
					icon: "GiLevelTwo",
				},
				sectionCertification: {
					component: "SectionCertificationOne",
					miniature: "MiniCertificationOne",
					item: "CardCertificationOne",
					Label: "Certification",
					icon: "PiCertificate",
				},
				sectionPrize: {
					component: "SectionPrizeOne",
					miniature: "MiniPrizeOne",
					item: "CardPrizeOne",
					Label: "Prix",
					icon: "PiMedal",
				},
				sectionPassion: {
					component: "SectionPassionOne",
					miniature: "MiniPassionOne",
					item: "CardPassionOne",
					Label: "Passion",
					icon: "BsBalloonHeartFill",
				},
				sectionExpertise: {
					component: "SectionExpertiseOne",
					miniature: "MiniExpertiseOne",
					item: "CardExpertiseOne",
					Label: "Expertise",
					icon: "RxMixerVertical",
				},
				sectionVolunteering: {
					component: "SectionVolunteeringOne",
					miniature: "MiniVolunteeringOne",
					item: "CardVolunteeringOne",
					Label: "Volontariat",
					icon: "MdOutlineVolunteerActivism",
				},
				sectionPublication: {
					component: "SectionPublicationOne",
					miniature: "MiniPublicationOne",
					item: "CardPublicationOne",
					Label: "Publication",
					icon: "MdArticle",
				},
				sectionAchievement: {
					component: "SectionAchievementOne",
					miniature: "MiniAchievementOne",
					item: "CardAchievementOne",
					Label: "Achievement",
					icon: "GiAchievement",
				},
				sectionCompetence: {
					component: "SectionCompetenceOne",
					miniature: "MiniCompetenceOne",
					item: "CardCompetenceOne",
					group: "CardGroupCompetenceOne",
					Label: "Compétence",
					icon: "MdTag",
				},
				sectionTag: {
					component: "SectionTagOne",
					miniature: "MiniTagOne",
					item: "CardTagOne",
					group: "CardGroupTagOne",
					Label: "Tag",
					icon: "MdTag",
				},
			},
		},
	},
	{
		name: "Moderne",
		structure: {
			layout: {
				...sharedLayout,
				typography: {
					fontFamily: "inter", // défaut user
					roles: {
						body: "inter",
						headerTitle: "playfair", // nom en serif
						headerSubTitle: "inter",
						sectionTitle: "lora", // titres section en Lora
					},
				},
				titleSection: {
					textTransform: "capitalize",
					withLigneDessous: true,
					withLigneDessus: false,
				},
			},
			header: buildHeader(moderneTokens),
			modules: [
				buildDescriptionModule(moderneTokens, { order: 1, title: "À propos" }),
				buildExperienceModule(moderneTokens, {
					order: 2,
					title: "Expériences",
				}),
				buildEducationModule(moderneTokens, { order: 3, title: "Diplomes" }),
				buildLanguageModule(moderneTokens, {
					order: 4,
					title: "Langues",
					design: "stars",
					isActive: false,
				}),
				buildSkillModule(moderneTokens, {
					order: 5,
					title: "Skills",
					design: "stars",
				}),
				buildCompetenceModule(moderneTokens, {
					order: 6,
					title: "Compétences",
					isActive: false,
				}),
				buildTagModule(moderneTokens, {
					order: 7,
					title: "Tags",
					isActive: false,
				}),
				buildSocialMediaModule(moderneTokens, {
					order: 8,
					title: "Réseaux sociaux",
				}),
				buildPassionModule(moderneTokens, {
					order: 9,
					title: "Passions",
					isActive: false,
				}),
				buildProjectModule(moderneTokens, { order: 10, title: "Projets" }),
				buildExpertiseModule(moderneTokens, {
					order: 11,
					title: "Expertises",
					isActive: false,
				}),
				buildStrengthModule(moderneTokens, {
					order: 12,
					title: "Atouts",
					isActive: false,
				}),
				buildPhilosophyModule(moderneTokens, {
					order: 13,
					title: "Philosophie",
					isActive: false,
				}),
				buildFormationModule(moderneTokens, {
					order: 14,
					title: "Formation",
					isActive: false,
				}),
				buildCertificationModule(moderneTokens, {
					order: 15,
					title: "Certifications",
					isActive: false,
				}),
				buildPrizeModule(moderneTokens, {
					order: 16,
					title: "Prix",
					isActive: false,
				}),
				buildPublicationModule(moderneTokens, {
					order: 17,
					title: "Publications",
					isActive: false,
				}),
				buildAchievementModule(moderneTokens, {
					order: 18,
					title: "Réalisations",
					isActive: false,
				}),
				buildVolunteeringModule(moderneTokens, {
					order: 19,
					title: "Volontariat",
					isActive: false,
				}),
			],
		},
		defaultStyles: {
			primaryColor: { name: "sky", primary: "-500" },
			slugTemplate: "moderne-noLine-x",
			components: {
				pageLayout: "OneColumnModel",
				sectionHeader: "HeaderTwo",
				sectionExperience: {
					component: "SectionExperienceOne",
					miniature: "MiniExperienceOne",
					item: "CardExperienceOne",
					Label: "Expérience",
					icon: "BsListCheck",
				},
				sectionDescription: {
					component: "SectionDescriptionOne",
					miniature: "MiniDescriptionOne",
					Label: "Présentation",
					icon: "BsPerson",
				},
				sectionEducation: {
					component: "SectionEducationOne",
					miniature: "MiniEducationOne",
					item: "CardEducationOne",
					Label: "Diplome",
					icon: "MdSchool",
				},
				sectionSkill: {
					component: "SectionSkillOne",
					miniature: "MiniSkillOne",
					item: "CardSkillOne",
					group: "CardGroupSkillOne",
					Label: "Skill",
					icon: "MdTag",
				},
				sectionLanguage: {
					component: "SectionLanguageOne",
					miniature: "MiniLanguageOne",
					item: "CardLanguageOne",
					Label: "Langue",
					icon: "MdLanguage",
				},
				sectionProject: {
					component: "SectionProjectOne",
					miniature: "MiniProjectOne",
					item: "CardProjectOne",
					Label: "Projet",
					icon: "GoProject",
				},
				sectionSocialMedia: {
					component: "SectionSocialMediaOne",
					miniature: "MiniSocialMediaOne",
					item: "CardSocialMediaOne",
					Label: "Réseau social",
					icon: "FaGlobe",
				},
				sectionStrength: {
					component: "SectionStrengthOne",
					miniature: "MiniStrengthOne",
					item: "CardStrengthOne",
					Label: "Atouts",
					icon: "FaThumbsUp",
				},
				sectionPhilosophy: {
					component: "SectionPhilosophyOne",
					miniature: "MiniPhilosophyOne",
					Label: "Philosophie",
					icon: "FaQuoteLeft",
				},
				sectionFormation: {
					component: "SectionFormationOne",
					miniature: "MiniFormationOne",
					item: "CardFormationOne",
					Label: "Formation",
					icon: "GiLevelTwo",
				},
				sectionCertification: {
					component: "SectionCertificationOne",
					miniature: "MiniCertificationOne",
					item: "CardCertificationOne",
					Label: "Certification",
					icon: "PiCertificate",
				},
				sectionPrize: {
					component: "SectionPrizeOne",
					miniature: "MiniPrizeOne",
					item: "CardPrizeOne",
					Label: "Prix",
					icon: "PiMedal",
				},
				sectionPassion: {
					component: "SectionPassionOne",
					miniature: "MiniPassionOne",
					item: "CardPassionOne",
					Label: "Passion",
					icon: "BsBalloonHeartFill",
				},
				sectionExpertise: {
					component: "SectionExpertiseOne",
					miniature: "MiniExpertiseOne",
					item: "CardExpertiseOne",
					Label: "Expertise",
					icon: "RxMixerVertical",
				},
				sectionVolunteering: {
					component: "SectionVolunteeringOne",
					miniature: "MiniVolunteeringOne",
					item: "CardVolunteeringOne",
					Label: "Volontariat",
					icon: "MdOutlineVolunteerActivism",
				},
				sectionPublication: {
					component: "SectionPublicationOne",
					miniature: "MiniPublicationOne",
					item: "CardPublicationOne",
					Label: "Publication",
					icon: "MdArticle",
				},
				sectionAchievement: {
					component: "SectionAchievementOne",
					miniature: "MiniAchievementOne",
					item: "CardAchievementOne",
					Label: "Achievement",
					icon: "GiAchievement",
				},
				sectionCompetence: {
					component: "SectionCompetenceOne",
					miniature: "MiniCompetenceOne",
					item: "CardCompetenceOne",
					group: "CardGroupCompetenceOne",
					Label: "Compétence",
					icon: "MdTag",
				},
				sectionTag: {
					component: "SectionTagOne",
					miniature: "MiniTagOne",
					item: "CardTagOne",
					group: "CardGroupTagOne",
					Label: "Tag",
					icon: "MdTag",
				},
			},
		},
	},
	{
		name: "Minimal",
		structure: {
			layout: {
				...sharedLayout,
				withPhoto: true,
				stylePhoto: "circle",
				listStyle: "line",
				titleSection: {
					withIcon: true,
					iconStyle: "flat",
					iconColor: "primaryColor",
					textTransform: "uppercase",
				},
			},
			header: buildHeader(minimalTokens),
			modules: [
				buildDescriptionModule(minimalTokens, {
					order: 1,
					title: "Présentation",
					isActive: false,
				}),
				buildExperienceModule(minimalTokens, {
					order: 2,
					title: "Expériences",
				}),
				buildEducationModule(minimalTokens, { order: 3, title: "Diplomes" }),
				buildLanguageModule(minimalTokens, {
					order: 4,
					title: "Langues",
					design: "bars",
				}),
				buildSkillModule(minimalTokens, {
					order: 5,
					title: "Skills",
					design: "bars",
				}),
				buildCompetenceModule(minimalTokens, {
					order: 6,
					title: "Compétences",
					isActive: false,
				}),
				buildTagModule(minimalTokens, {
					order: 7,
					title: "Tags",
					isActive: false,
				}),
				buildSocialMediaModule(minimalTokens, {
					order: 8,
					title: "Réseaux sociaux",
					isActive: false,
				}),
				buildPassionModule(minimalTokens, {
					order: 9,
					title: "Passions",
					isActive: false,
				}),
				buildProjectModule(minimalTokens, {
					order: 10,
					title: "Projets",
					isActive: false,
				}),
				buildExpertiseModule(minimalTokens, {
					order: 11,
					title: "Expertises",
					isActive: false,
				}),
				buildStrengthModule(minimalTokens, {
					order: 12,
					title: "Atouts",
					isActive: false,
				}),
				buildPhilosophyModule(minimalTokens, {
					order: 13,
					title: "Philosophie",
					isActive: false,
				}),
				buildFormationModule(minimalTokens, {
					order: 14,
					title: "Formation",
					isActive: false,
				}),
				buildCertificationModule(minimalTokens, {
					order: 15,
					title: "Certifications",
					isActive: false,
				}),
				buildPrizeModule(minimalTokens, {
					order: 16,
					title: "Prix",
					isActive: false,
				}),
				buildPublicationModule(minimalTokens, {
					order: 17,
					title: "Publications",
					isActive: false,
				}),
				buildAchievementModule(minimalTokens, {
					order: 18,
					title: "Réalisations",
					isActive: false,
				}),
				buildVolunteeringModule(minimalTokens, {
					order: 19,
					title: "Volontariat",
					isActive: false,
				}),
			],
		},
		defaultStyles: {
			primaryColor: { name: "lime", primary: "-500" },
			slugTemplate: "minimal-line-x",
			components: {
				pageLayout: "OneColumnModel",
				sectionHeader: "HeaderThree",
				sectionExperience: {
					component: "SectionExperienceTwo",
					miniature: "MiniExperienceOne",
					item: "CardExperienceOne",
					Label: "Expérience",
					icon: "BsListCheck",
				},
				sectionDescription: {
					component: "SectionDescriptionTwo",
					miniature: "MiniDescriptionOne",
					Label: "Présentation",
					icon: "BsPerson",
				},
				sectionEducation: {
					component: "SectionEducationTwo",
					miniature: "MiniEducationOne",
					item: "CardEducationOne",
					Label: "Diplome",
					icon: "MdSchool",
				},
				sectionSkill: {
					component: "SectionSkillTwo",
					miniature: "MiniSkillOne",
					item: "CardSkillOne",
					group: "CardGroupSkillOne",
					Label: "Skill",
					icon: "MdTag",
				},
				sectionLanguage: {
					component: "SectionLanguageTwo",
					miniature: "MiniLanguageOne",
					item: "CardLanguageOne",
					Label: "Langue",
					icon: "MdLanguage",
				},
				sectionProject: {
					component: "SectionProjectTwo",
					miniature: "MiniProjectOne",
					item: "CardProjectOne",
					Label: "Project",
					icon: "GoProject",
				},
				sectionSocialMedia: {
					component: "SectionSocialMediaTwo",
					miniature: "MiniSocialMediaOne",
					item: "CardSocialMediaOne",
					Label: "Réseau social",
					icon: "FaGlobe",
				},
				sectionStrength: {
					component: "SectionStrengthTwo",
					miniature: "MiniStrengthOne",
					item: "CardStrengthOne",
					Label: "Atouts",
					icon: "FaThumbsUp",
				},
				sectionPhilosophy: {
					component: "SectionPhilosophyTwo",
					miniature: "MiniPhilosophyOne",
					Label: "Philosophie",
					icon: "FaQuoteLeft",
				},
				sectionFormation: {
					component: "SectionFormationTwo",
					miniature: "MiniFormationOne",
					item: "CardFormationOne",
					Label: "Formation",
					icon: "GiLevelTwo",
				},
				sectionCertification: {
					component: "SectionCertificationTwo",
					miniature: "MiniCertificationOne",
					item: "CardCertificationOne",
					Label: "Certification",
					icon: "PiCertificate",
				},
				sectionPrize: {
					component: "SectionPrizeTwo",
					miniature: "MiniPrizeOne",
					item: "CardPrizeOne",
					Label: "Prix",
					icon: "PiMedal",
				},
				sectionPassion: {
					component: "SectionPassionTwo",
					miniature: "MiniPassionOne",
					item: "CardPassionOne",
					Label: "Passion",
					icon: "BsBalloonHeartFill",
				},
				sectionExpertise: {
					component: "SectionExpertiseTwo",
					miniature: "MiniExpertiseOne",
					item: "CardExpertiseOne",
					Label: "Expertise",
					icon: "RxMixerVertical",
				},
				sectionVolunteering: {
					component: "SectionVolunteeringTwo",
					miniature: "MiniVolunteeringOne",
					item: "CardVolunteeringOne",
					Label: "Volontariat",
					icon: "MdOutlineVolunteerActivism",
				},
				sectionPublication: {
					component: "SectionPublicationTwo",
					miniature: "MiniPublicationOne",
					item: "CardPublicationOne",
					Label: "Publication",
					icon: "MdArticle",
				},
				sectionAchievement: {
					component: "SectionAchievementTwo",
					miniature: "MiniAchievementOne",
					item: "CardAchievementOne",
					Label: "Achievement",
					icon: "GiAchievement",
				},
				sectionCompetence: {
					component: "SectionCompetenceTwo",
					miniature: "MiniCompetenceOne",
					item: "CardCompetenceOne",
					group: "CardGroupCompetenceOne",
					Label: "Compétence",
					icon: "MdTag",
				},
				sectionTag: {
					component: "SectionTagTwo",
					miniature: "MiniTagOne",
					item: "CardTagOne",
					group: "CardGroupTagOne",
					Label: "Tag",
					icon: "MdTag",
				},
			},
		},
	},
	{
		name: "Classique 1",
		structure: {
			layout: {
				...sharedLayout,
				withPhoto: false,
				titleSection: {
					...sharedLayout.titleSection,
					textAlign: "center",
				},
			},
			header: buildHeader(classiqueTokens),
			modules: [
				buildDescriptionModule(classiqueTokens, { order: 1, title: "Profil" }),
				buildExperienceModule(classiqueTokens, {
					order: 2,
					title: "Expériences professionnelles",
				}),
				buildEducationModule(classiqueTokens, { order: 3, title: "Diplomes" }),
				buildLanguageModule(classiqueTokens, {
					order: 4,
					title: "Langues",
					design: "stars",
				}),
				buildSkillModule(classiqueTokens, {
					order: 5,
					title: "Skills",
					isActive: false,
				}),
				buildCompetenceModule(classiqueTokens, {
					order: 6,
					title: "Compétences",
					isActive: false,
				}),
				buildTagModule(classiqueTokens, {
					order: 7,
					title: "Tags",
					isActive: false,
				}),
				buildSocialMediaModule(classiqueTokens, {
					order: 8,
					title: "Réseaux sociaux",
					isActive: false,
				}),
				buildPassionModule(classiqueTokens, {
					order: 9,
					title: "Passions",
					isActive: false,
				}),
				buildProjectModule(classiqueTokens, {
					order: 10,
					title: "Projets",
					isActive: false,
				}),
				buildExpertiseModule(classiqueTokens, {
					order: 11,
					title: "Expertises",
					isActive: false,
				}),
				buildStrengthModule(classiqueTokens, {
					order: 12,
					title: "Atouts",
					isActive: false,
				}),
				buildPhilosophyModule(classiqueTokens, {
					order: 13,
					title: "Philosophie",
					isActive: false,
				}),
				buildFormationModule(classiqueTokens, {
					order: 14,
					title: "Formation",
					isActive: false,
				}),
				buildCertificationModule(classiqueTokens, {
					order: 15,
					title: "Certifications",
					isActive: false,
				}),
				buildPrizeModule(classiqueTokens, {
					order: 16,
					title: "Prix",
					isActive: false,
				}),
				buildPublicationModule(classiqueTokens, {
					order: 17,
					title: "Publications",
					isActive: false,
				}),
				buildAchievementModule(classiqueTokens, {
					order: 18,
					title: "Réalisations",
					isActive: false,
				}),
				buildVolunteeringModule(classiqueTokens, {
					order: 19,
					title: "Volontariat",
					isActive: false,
				}),
				// language / project : mêmes builders une fois leurs schemas prêts
			],
		},
		defaultStyles: {
			primaryColor: { name: "red", primary: "-500" },
			slugTemplate: "classique-noLine-x",
			components: {
				pageLayout: "OneColumnModel",
				sectionHeader: "HeaderOne",
				sectionExperience: {
					component: "SectionExperienceOne",
					miniature: "MiniExperienceOne",
					item: "CardExperienceOne",
					Label: "Expérience",
					icon: "BsListCheck",
				},
				sectionDescription: {
					component: "SectionDescriptionOne",
					miniature: "MiniDescriptionOne",
					Label: "Présentation",
					icon: "BsPerson",
				},
				sectionEducation: {
					component: "SectionEducationOne",
					miniature: "MiniEducationOne",
					item: "CardEducationOne",
					Label: "Diplome",
					icon: "MdSchool",
				},
				sectionSkill: {
					component: "SectionSkillOne",
					miniature: "MiniSkillOne",
					item: "CardSkillOne",
					group: "CardGroupSkillOne",
					Label: "Skill",
					icon: "MdTag",
				},
				sectionLanguage: {
					component: "SectionLanguageOne",
					miniature: "MiniLanguageOne",
					item: "CardLanguageOne",
					Label: "Langue",
					icon: "MdLanguage",
				},
				sectionProject: {
					component: "SectionProjectOne",
					miniature: "MiniProjectOne",
					item: "CardProjectOne",
					Label: "Projet",
					icon: "GoProject",
				},
				sectionSocialMedia: {
					component: "SectionSocialMediaOne",
					miniature: "MiniSocialMediaOne",
					item: "CardSocialMediaOne",
					Label: "Réseau social",
					icon: "FaGlobe",
				},
				sectionStrength: {
					component: "SectionStrengthOne",
					miniature: "MiniStrengthOne",
					item: "CardStrengthOne",
					Label: "Atouts",
					icon: "FaThumbsUp",
				},
				sectionPhilosophy: {
					component: "SectionPhilosophyOne",
					miniature: "MiniPhilosophyOne",
					Label: "Philosophie",
					icon: "FaQuoteLeft",
				},
				sectionFormation: {
					component: "SectionFormationOne",
					miniature: "MiniFormationOne",
					item: "CardFormationOne",
					Label: "Formation",
					icon: "GiLevelTwo",
				},
				sectionCertification: {
					component: "SectionCertificationOne",
					miniature: "MiniCertificationOne",
					item: "CardCertificationOne",
					Label: "Certification",
					icon: "PiCertificate",
				},
				sectionPrize: {
					component: "SectionPrizeOne",
					miniature: "MiniPrizeOne",
					item: "CardPrizeOne",
					Label: "Prix",
					icon: "PiMedal",
				},
				sectionPassion: {
					component: "SectionPassionOne",
					miniature: "MiniPassionOne",
					item: "CardPassionOne",
					Label: "Passion",
					icon: "BsBalloonHeartFill",
				},
				sectionExpertise: {
					component: "SectionExpertiseOne",
					miniature: "MiniExpertiseOne",
					item: "CardExpertiseOne",
					Label: "Expertise",
					icon: "RxMixerVertical",
				},
				sectionVolunteering: {
					component: "SectionVolunteeringOne",
					miniature: "MiniVolunteeringOne",
					item: "CardVolunteeringOne",
					Label: "Volontariat",
					icon: "MdOutlineVolunteerActivism",
				},
				sectionPublication: {
					component: "SectionPublicationOne",
					miniature: "MiniPublicationOne",
					item: "CardPublicationOne",
					Label: "Publication",
					icon: "MdArticle",
				},
				sectionAchievement: {
					component: "SectionAchievementOne",
					miniature: "MiniAchievementOne",
					item: "CardAchievementOne",
					Label: "Achievement",
					icon: "GiAchievement",
				},
				sectionCompetence: {
					component: "SectionCompetenceOne",
					miniature: "MiniCompetenceOne",
					item: "CardCompetenceOne",
					group: "CardGroupCompetenceOne",
					Label: "Compétence",
					icon: "MdTag",
				},
				sectionTag: {
					component: "SectionTagOne",
					miniature: "MiniTagOne",
					item: "CardTagOne",
					group: "CardGroupTagOne",
					Label: "Tag",
					icon: "MdTag",
				},
			},
		},
	},
] satisfies SeedTemplate[];
